// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzQFPUr0QOJJH3BmiZDTNzbwVW9lmU78',
    appId: '1:682180946135:android:a80b2e089b790007ace892',
    messagingSenderId: '682180946135',
    projectId: 'myapp23758031',
    storageBucket: 'myapp23758031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2cPoablr1zdB-VtrwyaPt6eIBQdgS1LA',
    appId: '1:682180946135:ios:742f87013ea26ed5ace892',
    messagingSenderId: '682180946135',
    projectId: 'myapp23758031',
    storageBucket: 'myapp23758031.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3Zrvi0WvnbL-G8ElTy5ZXy0eSVEKKVo',
    appId: '1:682180946135:web:6c0e85d26bcb68c9ace892',
    messagingSenderId: '682180946135',
    projectId: 'myapp23758031',
    authDomain: 'myapp23758031.firebaseapp.com',
    storageBucket: 'myapp23758031.firebasestorage.app',
  );

}