# Generated by Django 5.2.7 on 2025-10-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('contact', models.CharField(max_length=50, verbose_name='Kontak')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('address', models.TextField(verbose_name='Alamat Pemasok')),
            ],
            options={
                'verbose_name': 'Pemasok',
                'verbose_name_plural': 'Pemasok',
            },
        ),
    ]
